import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { Box, ThemeIcon } from "@mantine/core";
import CatwikiLogo from "../components/CatWikiLogo";

const Home: NextPage = () => {
  return (
    <Box sx={{ maxWidth: "100%", margin: "1% 3%" }}>
      <Head>
        <title>Cat Wiki</title>
        <meta name="Cat Wiki" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box>
        <CatwikiLogo width="100" height="35" color="#291507" />
      </Box>
    </Box>
  );
};

export default Home;
